# Generated by Django 5.0.6 on 2024-07-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
