# Generated by Django 5.0.6 on 2024-07-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elism', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='products/default.png', upload_to='products/'),
        ),
    ]
