# Generated by Django 5.0.6 on 2024-07-05 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elism', '0004_producto_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='genero',
        ),
    ]
