# Generated by Django 5.0.6 on 2024-07-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elism', '0005_remove_producto_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoPerfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('imagen', models.ImageField(default='products/default.png', upload_to='products/')),
            ],
        ),
    ]
