# Generated by Django 5.0.6 on 2024-07-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elism', '0006_productoperfume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoperfume',
            name='imagen',
            field=models.ImageField(upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='productoperfume',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
