# Generated by Django 5.0.6 on 2024-07-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elism', '0007_alter_productoperfume_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoperfume',
            name='imagen',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
