# Generated by Django 5.0.6 on 2024-07-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elism', '0008_alter_productoperfume_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoperfume',
            name='imagen',
            field=models.ImageField(default='products/default.png', upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='productoperfume',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
