# Generated by Django 5.0.6 on 2024-07-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elism', '0010_carrito_delete_productoperfume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
