# Generated by Django 5.0.6 on 2024-07-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elism', '0013_contacto_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
